/**
 * Human-readable labels for common Tailwind CSS classes.
 * Shown in autocomplete dropdown alongside the class name,
 * and in chip tooltips for non-technical users.
 */
export const FRIENDLY_LABELS: Record<string, string> = {
  // --- Display & Layout ---
  flex: 'Side by side',
  'flex-col': 'Stacked vertically',
  'flex-row': 'Side by side (row)',
  grid: 'Grid layout',
  block: 'Full width block',
  'inline-block': 'Inline block',
  inline: 'Inline (no line break)',
  hidden: 'Hidden (invisible)',
  contents: 'No wrapper box',

  // --- Flex alignment ---
  'items-center': 'Center items vertically',
  'items-start': 'Align items to top',
  'items-end': 'Align items to bottom',
  'items-stretch': 'Stretch items to fill',
  'justify-center': 'Center items horizontally',
  'justify-between': 'Space evenly between',
  'justify-around': 'Space around items',
  'justify-start': 'Push items to left',
  'justify-end': 'Push items to right',
  'justify-evenly': 'Equal spacing everywhere',
  'flex-wrap': 'Wrap to next line',
  'flex-nowrap': 'Never wrap',
  'gap-1': 'Tiny gap between items',
  'gap-2': 'Small gap between items',
  'gap-4': 'Medium gap between items',
  'gap-6': 'Large gap between items',
  'gap-8': 'Extra large gap between items',

  // --- Padding ---
  'p-0': 'No padding',
  'p-1': 'Tiny padding (4px)',
  'p-2': 'Small padding (8px)',
  'p-3': 'Medium-small padding (12px)',
  'p-4': 'Medium padding (16px)',
  'p-5': 'Medium-large padding (20px)',
  'p-6': 'Large padding (24px)',
  'p-8': 'Extra large padding (32px)',
  'p-10': 'Huge padding (40px)',
  'p-12': 'Very large padding (48px)',
  'p-16': 'Massive padding (64px)',
  'px-2': 'Small left & right padding',
  'px-4': 'Medium left & right padding',
  'px-6': 'Large left & right padding',
  'px-8': 'Extra large left & right padding',
  'py-2': 'Small top & bottom padding',
  'py-4': 'Medium top & bottom padding',
  'py-6': 'Large top & bottom padding',
  'py-8': 'Extra large top & bottom padding',
  'pt-2': 'Small top padding',
  'pt-4': 'Medium top padding',
  'pb-2': 'Small bottom padding',
  'pb-4': 'Medium bottom padding',
  'pl-2': 'Small left padding',
  'pl-4': 'Medium left padding',
  'pr-2': 'Small right padding',
  'pr-4': 'Medium right padding',

  // --- Margin ---
  'm-0': 'No margin',
  'm-1': 'Tiny margin (4px)',
  'm-2': 'Small margin (8px)',
  'm-4': 'Medium margin (16px)',
  'm-6': 'Large margin (24px)',
  'm-8': 'Extra large margin (32px)',
  'm-auto': 'Center with auto margin',
  'mx-auto': 'Center horizontally',
  'mx-2': 'Small left & right margin',
  'mx-4': 'Medium left & right margin',
  'my-2': 'Small top & bottom margin',
  'my-4': 'Medium top & bottom margin',
  'my-6': 'Large top & bottom margin',
  'my-8': 'Extra large top & bottom margin',
  'mt-2': 'Small top margin',
  'mt-4': 'Medium top margin',
  'mt-6': 'Large top margin',
  'mt-8': 'Extra large top margin',
  'mb-2': 'Small bottom margin',
  'mb-4': 'Medium bottom margin',
  'mb-6': 'Large bottom margin',
  'mb-8': 'Extra large bottom margin',
  'ml-auto': 'Push left (auto left margin)',
  'mr-auto': 'Push right (auto right margin)',

  // --- Sizing ---
  'w-full': 'Full width',
  'w-auto': 'Auto width',
  'w-1/2': 'Half width (50%)',
  'w-1/3': 'One third width (33%)',
  'w-2/3': 'Two thirds width (66%)',
  'w-1/4': 'Quarter width (25%)',
  'w-3/4': 'Three quarters width (75%)',
  'w-screen': 'Full screen width',
  'h-full': 'Full height',
  'h-auto': 'Auto height',
  'h-screen': 'Full screen height',
  'min-w-full': 'At least full width',
  'max-w-sm': 'Max width: small',
  'max-w-md': 'Max width: medium',
  'max-w-lg': 'Max width: large',
  'max-w-xl': 'Max width: extra large',
  'max-w-2xl': 'Max width: 2x large',
  'max-w-full': 'Max width: 100%',
  'max-w-prose': 'Max width: readable text',

  // --- Typography ---
  'text-xs': 'Tiny text',
  'text-sm': 'Small text',
  'text-base': 'Normal text',
  'text-lg': 'Large text',
  'text-xl': 'Extra large text',
  'text-2xl': 'Heading size',
  'text-3xl': 'Large heading',
  'text-4xl': 'Very large heading',
  'text-5xl': 'Huge heading',
  'font-thin': 'Thin weight',
  'font-light': 'Light weight',
  'font-normal': 'Normal weight',
  'font-medium': 'Medium weight',
  'font-semibold': 'Semi-bold',
  'font-bold': 'Bold',
  'font-extrabold': 'Extra bold',
  'font-black': 'Black (heaviest)',
  italic: 'Italic',
  'not-italic': 'Not italic',
  underline: 'Underline',
  'line-through': 'Strikethrough',
  'no-underline': 'Remove underline',
  uppercase: 'ALL CAPS',
  lowercase: 'all lowercase',
  capitalize: 'Capitalize Words',
  'text-left': 'Left aligned',
  'text-center': 'Centered text',
  'text-right': 'Right aligned',
  truncate: 'Cut off with ellipsis',
  'leading-tight': 'Tight line height',
  'leading-normal': 'Normal line height',
  'leading-relaxed': 'Relaxed line height',
  'leading-loose': 'Loose line height',
  'tracking-tight': 'Tight letter spacing',
  'tracking-wide': 'Wide letter spacing',
  'tracking-widest': 'Very wide letter spacing',

  // --- Common text colors ---
  'text-white': 'White text',
  'text-black': 'Black text',
  'text-gray-400': 'Light gray text',
  'text-gray-500': 'Medium gray text',
  'text-gray-600': 'Dark gray text',
  'text-gray-700': 'Darker gray text',
  'text-gray-900': 'Near-black text',
  'text-red-500': 'Red text',
  'text-red-600': 'Dark red text',
  'text-blue-500': 'Blue text',
  'text-blue-600': 'Dark blue text',
  'text-green-500': 'Green text',
  'text-green-600': 'Dark green text',
  'text-yellow-500': 'Yellow text',
  'text-purple-500': 'Purple text',
  'text-pink-500': 'Pink text',
  'text-indigo-500': 'Indigo text',
  'text-orange-500': 'Orange text',

  // --- Background colors ---
  'bg-white': 'White background',
  'bg-black': 'Black background',
  'bg-transparent': 'Transparent background',
  'bg-gray-50': 'Very light gray background',
  'bg-gray-100': 'Light gray background',
  'bg-gray-200': 'Gray background',
  'bg-gray-800': 'Dark gray background',
  'bg-gray-900': 'Very dark background',
  'bg-red-500': 'Red background',
  'bg-blue-500': 'Blue background',
  'bg-blue-600': 'Dark blue background',
  'bg-green-500': 'Green background',
  'bg-yellow-400': 'Yellow background',
  'bg-purple-500': 'Purple background',
  'bg-pink-500': 'Pink background',
  'bg-indigo-500': 'Indigo background',
  'bg-orange-500': 'Orange background',

  // --- Border ---
  border: 'Thin border',
  'border-2': 'Medium border',
  'border-4': 'Thick border',
  'border-0': 'No border',
  'border-t': 'Top border only',
  'border-b': 'Bottom border only',
  'border-l': 'Left border only',
  'border-r': 'Right border only',
  'border-dashed': 'Dashed border',
  'border-dotted': 'Dotted border',
  'border-solid': 'Solid border',
  'border-gray-200': 'Light gray border',
  'border-gray-300': 'Gray border',
  'border-gray-400': 'Medium gray border',
  'border-blue-500': 'Blue border',
  'border-red-500': 'Red border',
  'border-green-500': 'Green border',

  // --- Border radius ---
  'rounded-none': 'Square corners',
  'rounded-sm': 'Slightly rounded',
  rounded: 'Rounded corners',
  'rounded-md': 'Moderately rounded',
  'rounded-lg': 'Very rounded',
  'rounded-xl': 'Extra rounded',
  'rounded-2xl': 'More rounded',
  'rounded-3xl': 'Very extra rounded',
  'rounded-full': 'Pill / circle shape',
  'rounded-t': 'Round top corners',
  'rounded-b': 'Round bottom corners',
  'rounded-l': 'Round left corners',
  'rounded-r': 'Round right corners',

  // --- Shadow ---
  'shadow-none': 'No shadow',
  'shadow-sm': 'Subtle shadow',
  shadow: 'Small shadow',
  'shadow-md': 'Medium shadow',
  'shadow-lg': 'Large shadow',
  'shadow-xl': 'Extra large shadow',
  'shadow-2xl': 'Very large shadow',
  'shadow-inner': 'Inner shadow',

  // --- Opacity ---
  'opacity-0': 'Invisible',
  'opacity-25': '25% visible',
  'opacity-50': '50% visible',
  'opacity-75': '75% visible',
  'opacity-100': 'Fully visible',

  // --- Overflow ---
  'overflow-hidden': 'Hide overflow',
  'overflow-auto': 'Scroll if needed',
  'overflow-scroll': 'Always scrollable',
  'overflow-visible': 'Show overflow',
  'overflow-x-auto': 'Scroll left/right if needed',
  'overflow-y-auto': 'Scroll up/down if needed',
  'overflow-x-hidden': 'Hide left/right overflow',
  'overflow-y-hidden': 'Hide up/down overflow',

  // --- Position ---
  relative: 'Relative position',
  absolute: 'Absolute position',
  fixed: 'Fixed to screen',
  sticky: 'Sticky (scrolls then fixes)',
  static: 'Normal position',
  'inset-0': 'Fill parent completely',
  'top-0': 'Pinned to top',
  'bottom-0': 'Pinned to bottom',
  'left-0': 'Pinned to left',
  'right-0': 'Pinned to right',

  // --- Z-index ---
  'z-0': 'Normal stacking',
  'z-10': 'Above most elements',
  'z-20': 'Further above',
  'z-30': 'Even higher',
  'z-40': 'Near the top',
  'z-50': 'On top of everything',
  '-z-10': 'Behind elements',

  // --- Cursor ---
  'cursor-pointer': 'Hand cursor (clickable)',
  'cursor-default': 'Normal cursor',
  'cursor-not-allowed': 'Not allowed cursor',
  'cursor-wait': 'Loading cursor',
  'cursor-move': 'Move cursor',
  'cursor-text': 'Text cursor',
  'cursor-grab': 'Grab cursor',

  // --- Interactivity ---
  'pointer-events-none': 'Ignore mouse clicks',
  'pointer-events-auto': 'Allow mouse clicks',
  'select-none': 'Prevent text selection',
  'select-text': 'Allow text selection',

  // --- Transitions ---
  transition: 'Smooth transitions',
  'transition-all': 'Animate everything',
  'transition-colors': 'Animate colors',
  'transition-opacity': 'Animate opacity',
  'transition-transform': 'Animate movement',
  'duration-150': 'Fast transition (150ms)',
  'duration-200': 'Quick transition (200ms)',
  'duration-300': 'Normal transition (300ms)',
  'duration-500': 'Slow transition (500ms)',
  'ease-in': 'Starts slow',
  'ease-out': 'Ends slow',
  'ease-in-out': 'Starts and ends slow',

  // --- Transforms ---
  'scale-95': 'Slightly shrunk',
  'scale-100': 'Normal size',
  'scale-105': 'Slightly larger',
  'scale-110': 'Noticeably larger',
  'rotate-45': 'Rotate 45°',
  'rotate-90': 'Rotate 90°',
  'rotate-180': 'Flipped upside-down',

  // --- Animations ---
  'animate-spin': 'Spinning animation',
  'animate-pulse': 'Pulsing animation',
  'animate-bounce': 'Bouncing animation',
  'animate-ping': 'Ping ripple animation',
  'animate-none': 'No animation',

  // --- Accessibility ---
  'sr-only': 'Screen reader only (visually hidden)',
  'not-sr-only': 'Visible (undo sr-only)',

  // --- Aspect Ratio ---
  'aspect-square': 'Square (1:1 ratio)',
  'aspect-video': 'Video (16:9 ratio)',
  'aspect-auto': 'Natural aspect ratio',

  // --- Object fit ---
  'object-cover': 'Cover and crop image',
  'object-contain': 'Fit image inside',
  'object-fill': 'Stretch image to fill',
  'object-none': 'No resizing',

  // --- Columns ---
  'grid-cols-1': '1 column',
  'grid-cols-2': '2 columns',
  'grid-cols-3': '3 columns',
  'grid-cols-4': '4 columns',
  'grid-cols-6': '6 columns',
  'grid-cols-12': '12 columns',
  'col-span-1': 'Span 1 column',
  'col-span-2': 'Span 2 columns',
  'col-span-3': 'Span 3 columns',
  'col-span-full': 'Span all columns',

  // --- Whitespace ---
  'whitespace-nowrap': 'No line wrapping',
  'whitespace-pre': 'Preserve whitespace',
  'whitespace-normal': 'Normal wrapping',

  // --- Visibility ---
  visible: 'Visible',
  invisible: 'Invisible (keeps space)',
};

export default FRIENDLY_LABELS;
